---
- name: install required python deps
  become: yes
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
    - python-netaddr

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: zsh.yml
