- name: install base packages
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  become: yes
  with_items:
    - bash-completion
    - vim
    - git
    - git-core
    - git-email
    - git-extras
    - curl
    - jq
    - wget
    - htop
    - unzip
    - tar
    - gzip
    - bzip2
    - build-essential
    - gcc
    - g++
