---
- name: install dependencies
  become: yes
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - git
    - zsh

- name: clone oh-my-zsh for users
  tags:
    - skip_ansible_lint
  become: yes
  # core.autocrlf=input prevents https://github.com/robbyrussell/oh-my-zsh/issues/4402
  command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git /etc/.oh-my-zsh'
  args:
    creates: '/etc/.oh-my-zsh'

- name: set ownership and permissions of oh-my-zsh for users
  become: yes
  file:
    path: '/etc/.oh-my-zsh'
    owner: 'root'
    group: "root"
    mode: 'go-w'
    recurse: yes

- name: set zsh cache dir
  become: yes
  command: "mkdir -p /etc/skel/.oh-my-zsh/cache"

- name: write .zshrc for users
  become: yes
  template:
    src: zshrc.j2
    dest: '/etc/skel/.zshrc'
    backup: yes
    owner: 'root'
    group: "root"
    mode: 'u=rw,go=r'
  with_items: '{{ users }}'

- name: set default shell to zsh
  become: yes
  template:
    src: useradd.j2
    dest: '/etc/default/useradd'
    backup: yes
    owner: 'root'
    group: "root"
    mode: 'u=rw,go=r'
