---
- name: install dependencies
  become: yes
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - git
    - zsh

- name: clone oh-my-zsh for users
  tags:
    - skip_ansible_lint
  become: yes
  # core.autocrlf=input prevents https://github.com/robbyrussell/oh-my-zsh/issues/4402
  command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git ~{{ item.username }}/.oh-my-zsh'
  args:
    creates: '~{{ item.username }}/.oh-my-zsh'
  with_items: '{{ users }}'

- name: set ownership and permissions of oh-my-zsh for users
  become: yes
  file:
    path: '~{{ item.username }}/.oh-my-zsh'
    owner: '{{ item.username }}'
    group: "{{ (ansible_os_family == 'Suse') | ternary('users', item.username) }}"
    mode: 'go-w'
    recurse: yes
  with_items: '{{ users }}'

- name: set default shell for users
  become: yes
  user:
    name: '{{ item.username }}'
    shell: /bin/zsh
  with_items: '{{ users }}'

- name: write .zshrc for users
  become: yes
  template:
    src: zshrc.j2
    dest: '~{{ item.username }}/.zshrc'
    backup: yes
    owner: '{{ item.username }}'
    group: "{{ (ansible_os_family == 'Suse') | ternary('users', item.username) }}"
    mode: 'u=rw,go=r'
  with_items: '{{ users }}'
